name: Build LaTeX document
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Rename file 
        run: mv main.pdf layangelo-latex.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: layangelo-latex.pdf